import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Financial Disclaimer',
  description: 'ScraperAgent financial disclaimer — not financial advice. AI-generated market analysis for informational purposes only.',
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-3xl font-bold text-text-primary mb-2">Financial Disclaimer</h1>
      <p className="text-sm text-text-muted mb-10">Last updated: February 2026</p>

      <div className="prose-sm space-y-8 text-text-secondary leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Not Financial Advice</h2>
          <p>
            ScraperAgent is an AI-powered market analysis tool operated by Kovimatic (kovimatic.ie).
            The reports, signals, sentiment analysis, recommendations, and any other content provided
            through this service are for <strong>informational purposes only</strong> and do not
            constitute financial, investment, trading, or other professional advice.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">No Licensed Advisors</h2>
          <p>
            Kovimatic does not employ licensed financial advisors. No content produced by ScraperAgent
            should be interpreted as a recommendation to buy, sell, or hold any security, cryptocurrency,
            or financial instrument.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">AI-Generated Content</h2>
          <p>
            All analysis is generated by artificial intelligence based on
            publicly available tweets from market commentators on X (Twitter). AI models can and do
            produce inaccurate, incomplete, or misleading information. The AI may misinterpret expert
            opinions, fabricate data points, or fail to account for critical market factors.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">No Guarantees</h2>
          <p>
            Past analysis performance does not indicate future results. Market conditions can change
            rapidly and without warning. The sentiment scores, trading signals, and recommendations
            generated by ScraperAgent may be wrong. You should never rely solely on this service for
            investment decisions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Your Responsibility</h2>
          <p>
            You are solely responsible for your own investment decisions. Before making any financial
            decision, consult with a qualified financial advisor who understands your personal financial
            situation, risk tolerance, and investment objectives.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Data Sources</h2>
          <p>
            All source data is derived from publicly posted content on X (Twitter). ScraperAgent does
            not have access to proprietary research, insider information, or non-public data. The experts
            tracked are public market commentators; their inclusion does not imply endorsement of this
            service, nor does it imply any relationship between ScraperAgent and the expert.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Limitation of Liability</h2>
          <p>
            Kovimatic and ScraperAgent shall not be held liable for any losses, damages, or costs
            arising from the use of this service or reliance on its content. Use at your own risk.
            In no event shall our aggregate liability exceed the amount you have paid for the service
            in the preceding 12 months.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Contact</h2>
          <p>
            Questions about this disclaimer? Contact us at{' '}
            <a href="mailto:it@kovimatic.ie" className="text-blue-400 hover:text-blue-300 transition-colors">
              it@kovimatic.ie
            </a>.
          </p>
          <p className="mt-2">
            Company: Kovimatic, Ireland —{' '}
            <a href="https://kovimatic.ie" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 transition-colors">
              kovimatic.ie
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
