location                = "westeurope"
resource_group_name     = "rg-scraperagent"
vm_size                 = "Standard_B1ms"
dns_zone_name           = "scraperagent.eu"
dns_zone_resource_group = "ne-mgmt-s01"
api_subdomain           = "api"
