import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'ScraperAgent terms of service — subscription terms, free trial details, and usage conditions.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-3xl font-bold text-text-primary mb-2">Terms of Service</h1>
      <p className="text-sm text-text-muted mb-10">Last updated: February 2026</p>

      <div className="prose-sm space-y-8 text-text-secondary leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Service Description</h2>
          <p>
            ScraperAgent is an AI-powered market intelligence service that delivers daily analysis
            reports via email. Reports are generated by analyzing publicly available expert commentary
            on X (Twitter) using artificial intelligence.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Eligibility</h2>
          <p>
            You must be at least 18 years old to use ScraperAgent. By subscribing, you confirm that
            you are of legal age and have the capacity to enter into these terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Free Trial</h2>
          <p>
            New subscribers receive 10 free reports within a 14-day trial period. After the trial
            ends (either all 10 reports are delivered or 14 days elapse), report delivery pauses
            until you subscribe to a paid plan. There are no automatic charges — you must explicitly
            choose to upgrade.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Subscription & Payments</h2>
          <p>
            After the free trial, ScraperAgent is available for €9.99/month (EUR). Payments are
            processed securely through our payment provider. You can cancel at any time from your
            management page — cancellation takes effect at the end of the current billing period.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Account</h2>
          <p>
            One subscription per email address. You are responsible for maintaining the confidentiality
            of your management token. If you believe your account has been compromised, contact us
            immediately at{' '}
            <a href="mailto:it@kovimatic.ie" className="text-blue-400 hover:text-blue-300 transition-colors">
              it@kovimatic.ie
            </a>.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Intellectual Property</h2>
          <p>
            Reports generated by ScraperAgent are provided for your personal, non-commercial use.
            You may not redistribute, resell, or publish our reports without written permission.
            The ScraperAgent name, logo, and branding are property of Kovimatic.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Content Accuracy</h2>
          <p>
            ScraperAgent reports are AI-generated and may contain inaccuracies. We make no warranties
            regarding the accuracy, completeness, or reliability of the analysis. See our{' '}
            <a href="/disclaimer" className="text-blue-400 hover:text-blue-300 transition-colors">
              Financial Disclaimer
            </a>{' '}
            for full details.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Kovimatic shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages arising from your use of ScraperAgent.
            Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Termination</h2>
          <p>
            Either party may terminate the subscription at any time. You can cancel from your management
            page (linked in every email). We reserve the right to terminate accounts that violate these
            terms or engage in abusive behavior.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Governing Law</h2>
          <p>
            These terms are governed by the laws of Ireland. Any disputes shall be subject to the
            exclusive jurisdiction of the courts of Ireland.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-text-primary mb-2">Contact</h2>
          <p>
            Questions about these terms? Contact us at{' '}
            <a href="mailto:it@kovimatic.ie" className="text-blue-400 hover:text-blue-300 transition-colors">
              it@kovimatic.ie
            </a>.
          </p>
          <p className="mt-2">
            Company: Kovimatic, Ireland —{' '}
            <a href="https://kovimatic.ie" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 transition-colors">
              kovimatic.ie
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
