use_default_settings: true

general:
  instance_name: "ScraperAgent Search"
  debug: false

server:
  secret_key: "<SEARXNG_SECRET_KEY>"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json
